### ISSUE TITLE
advanced indexing is not supported

### ISSUE THREAD

**Issue by maxxxzdn** [QUVA-Lab/escnn#10]
Hi @Gabri95,

So far, only basic slicing is supported. Would be cool to have advanced indexing :).

```
import torch
import escnn
print(escnn.__version__)
from escnn import nn, group, gspaces

G = group.so3_group()
gspace = gspaces.no_base_space(G)
in_type = gspace.type(G.standard_representation()) # input: 3D coordinates
x = nn.GeometricTensor(torch.randn(10,3), in_type)
indices = torch.randint(0, 10, (5,))
```
Slicing would work: 
`print(x[1:5])`

But indexing will give an error:
`print(x[indices])`

**Comment by Gabri95** [comment]
Hi @maxxxzdn 

Thanks for opening this issue!
I've implemented some advanced indexing features, but I'm not sure if all advanced indexing features of PyTorch are supported.
In any case, this should at least cover your use case 

Let me know if you find some missing features!

Best,
Gabriele
