### ISSUE TITLE
GNormBatchNorm does not work for quotient representation

### ISSUE THREAD

**Issue by maxxxzdn** [QUVA-Lab/escnn#17]
Hi Gabriele, 

I have been playing with different Batch Norms recently and GNormBatchNorm did not quite work for me (see pic).

Do you know what it the problem here?
![image](https://user-images.githubusercontent.com/50237680/196007262-ca27f3e1-d416-40d1-a141-da428ce7a675.png)

**Comment by Gabri95** [comment]
hey!

Sorry about this, but GNormBatchNorm is an old layer developed for e2cnn, so it assumes images in input (it assumes the input has shape 4).
Thanks for spotting this issue, I will fix it asap!


By the way, why are you passing `in_type` twice to GNormBatchNorm?

Best,
Gabriele

**Comment by maxxxzdn** [comment]
I see, thanks for clarifying! 
Oops, my bad, I initially was playing with another module and naively substituted one with another :)
