### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by loicsacre** [QUVA-Lab/escnn#21]
I am unable to install the package. The problem is coming from the package `py3nj` for which I am unable to build the wheel. I have posted an issue on the repo, please take a look at https://github.com/fujiisoup/py3nj/issues/18

Does anyone also have installation issues ?

**Comment by Gabri95** [comment]
Hi @loicsacre 

On a Linux machine, I had to first run `apt install gfortran` and then I could install `py3nj` via pip without any issues.

Could you try that?

**Comment by Danfoa** [comment]
py3nj seems to be not maintained, and there are issues with new version of setuptools and numpy due to deprecated features. 

How relevant is py3nj?  It is perhaps a bad strategy to depend on abandoned packages.
