### ISSUE TITLE
strided r2conv operations as pooling substitute fails to construct

### ISSUE THREAD

**Issue by psteinb** [QUVA-Lab/escnn#39]
I was playing with strided convolutions as a pooling operation that retains equivariance (more robustly than Avg/MaxPool). For this, I was testing a simple setup:

``` python
def test_r2conv_fails_with_ksize2_stride2():

    reg_sconv = torch.nn.Conv2d(64, 64, kernel_size=2, stride=2, padding=1)
    assert hasattr(reg_sconv, "forward")

    gspace = gspaces.rot2dOnR2(N=4)
    iotype = nn.FieldType(gspace, 16 * [gspace.regular_repr])

    poolop = nn.R2Conv(
            iotype, iotype, kernel_size=2, stride=2, padding=1, bias=False
        )
    assert hasattr(poolop, "forward")
```

Unfortunately, the `nn.R2Conv` constructor triggers a ValueError:
```
E           ValueError: 
E                           The basis for the steerable filter is empty!
E                           Tune the `frequencies_cutoff`, `kernel_size`, `rings`, `sigma` or `basis_filter` parameters to allow
E                           for a larger basis.

py310/lib64/python3.10/site-packages/escnn/nn/modules/conv/rd_convolution.py:230: ValueError
```
I was trying to debug this, but couldn't get any insights out of this function 
https://github.com/QUVA-Lab/escnn/blob/97a34e8a3061ac150b62e9613d3734ff6ec4c22c/escnn/nn/modules/conv/r2convolution.py#L386

**Comment by Gabri95** [comment]
Hi @psteinb 

I would not recommend using kernels with even dimension (`kernel_size=2`).
Also, in practice, a 2x2 grid is too small to sample steerable filters.

Check [this older issue](https://github.com/QUVA-Lab/e2cnn/issues/18) for a detailed explanation.

Best,
Gabriele

**Comment by psteinb** [comment]
Hey @Gabri95 ... thanks for the quick response. The issue you pointed to really helps. It would be great, if such high quality content could be part of the `escnn` docs.
