### ISSUE TITLE
Blog post about escnn: https://blogs.rstudio.com/ai/posts/2023-05-09-group-equivariant-cnn-3/

### ISSUE THREAD

**Issue by skeydan** [QUVA-Lab/escnn#44]
Hi @Gabri95, 

just wanted to let you (and maybe others who could be interested in this) know that I've written a post about `escnn` that

- uses  `escnn` from R, by means of the interface package `reticulate`
- provides a high-level introduction to how the math, the code, and the task to be solved go together (I call it an "introduction to an introduction" - the latter being your `introduction.ipynb`)

Here it is: https://blogs.rstudio.com/ai/posts/2023-05-09-group-equivariant-cnn-3/

Of course, close this issue any time, - I'm just taking the opportunity for a "sales pitch" of sorts ;-)):
In R, we have a port of PyTorch, as well as a steadily growing ecosystem based on it: see 

https://github.com/mlverse/torch
https://github.com/mlverse

So in case someone reads this and could imagine porting `escnn`, we'd be more than happy to help :-)
Thanks!

**Comment by Gabri95** [comment]
Hi @skeydan 

Really cool, thanks a lot for using our work and for helping us reaching the R community!

I have just opened the "Discussions" section, maybe that's a more appropriate place to advertise this after I close this issue.

Thanks again!
Gabriele
