### ISSUE TITLE
TypeError: 'SequentialModule' object is not subscriptable

### ISSUE THREAD

**Issue by maxxxzdn** [QUVA-Lab/escnn#6]
Hi Gabriele, 

It seems that SequentialModule is not subscribable now. 

to reproduce:

```
from escnn import group
from escnn import gspaces
from escnn import nn

G = group.so3_group()
gspace = gspaces.no_base_space(G)
in_type = gspace.type(G.standard_representation())

seq = nn.SequentialModule(nn.IIDBatchNorm1d(in_type), nn.IIDBatchNorm1d(in_type))
print(seq[0])
```

**Comment by Gabri95** [comment]
Hi @maxxxzdn 

Thanks for pointing out this issue.
My implementation of  SequentialModule was based on an older version of PyTorch which didn't have these features.

I have now added most of the recent features, including indexing, slicing and iterating.

Best,
Gabriele
