### ISSUE TITLE
Export linear layer

### ISSUE THREAD

**Issue by theyearis1981** [QUVA-Lab/escnn#61]
Hi!

I am trying to export a network containing linear layers, but I'm getting the following error:

File "X/site-packages/escnn/nn/modules/linear.py", line 305, in export
linear.weight.data[:] = self
TypeError: can't assign a Linear to a torch.FloatTensor

Do you know what's causing it?

Thanks!

**Comment by chAwater** [comment]
@theyearis1981 @Gabri95 I think this is a bug, this line of code should be removed.
https://github.com/QUVA-Lab/escnn/blob/0e8d301f4ede5478303d1354299e6ec4440afd2e/escnn/nn/modules/linear.py#L305
https://github.com/QUVA-Lab/escnn/blob/0e8d301f4ede5478303d1354299e6ec4440afd2e/escnn/nn/modules/linear.py#L289-L312
