### ISSUE TITLE
check_equivariance test failed

### ISSUE THREAD

**Issue by Guptajakala** [QUVA-Lab/escnn#71]
```
gspace = gspaces.rot2dOnR2(4)
n_feat = 16
in_type = enn.FieldType(gspace, [gspace.trivial_repr]*3)
out_type = enn.FieldType(gspace, [gspace.regular_repr]*n_feat)

net = enn.R2Conv(in_type, out_type, kernel_size=3, stride=1, padding=1, dilation=1, bias=True, sigma=None)
net.check_equivariance()
```
I got error `AssertionError: The error found during equivariance check with element "10[2pi/12]" is too high: max = 3.4398996829986572, mean = 0.3915270268917084 var =0.21077707409858704`

Is this failure expected?

**Comment by Gabri95** [comment]
Hi @Guptajakala 

Are you sure this is the code you run to generate this error?
The group you are choosing in the line `gspace = gspaces.rot2dOnR2(4)` only contains (multiples of) 90 degrees rotations but the error you report says the model failed at the rotation `5/6 * 2pi` which doesn't belong to this group.


Best,
Gabriele

**Comment by Guptajakala** [comment]
I found it was caused by a mistake. Now I run with the right code, it's all good.
