### ISSUE TITLE
Can escnn be used to process one-dimensional data?

### ISSUE THREAD

**Issue by wgimmy** [QUVA-Lab/escnn#96]
hi,I am currently studying the problem of spatial transformation of molecular diffusion trajectories. The data used is a matrix with two rows and n columns. However, unlike image data, if the numbers in the matrix are regarded as pixel values ​​of the image, after multiplying the matrix by a rotation matrix, the value of the corresponding position will change (the corresponding position of the real picture is rotated The pixel value is unchanged) so I am not sure whether escnn can be applied to one-dimensional data. Can you give me some suggestions?

**Comment by maxxxzdn** [comment]
Generally, escnn supports 2D and 3D grids, as well as irregular grids (e.g. point clouds). Usually, that is how people work with molecular data - cast is a a graph with features (I assume that is the feature matrix you are talking about) and run point convolutions. 

escnn totally supports that; check out this example https://github.com/maxxxzdn/implicit-steerable-kernels/blob/main/examples/3_point_conv.ipynb
